#!/usr/bin/env python3
"""Table 3: per-workload MAPE summary across data regimes (tab:mape_summary).

Reproduces the table generated by revision/TableA -> writes figures/table3.tex.

Uses BOTH:
  * the DRAMPower power model (sources/drampower -> HBM2_runner), and
  * empirical per-chip ground truth (data/ground_truth_{allzeros,random}.csv).

For each (model, data pattern) it runs HBM2_runner once per workload trace, computes the
per-workload MAPE against the per-chip ground truth, then reports the min / max / mean of
those 14 per-workload MAPEs (6 microbenchmarks + the 8-point LLaMa3.1-8B decode sweep).
Three models x two regimes: DRAMSim3, FGDRAM HBM2, Ours.
"""
import os
import re, csv, subprocess, sys
from pathlib import Path
from collections import defaultdict

REPO_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR  = Path(os.environ.get("DATA_DIR", str(REPO_ROOT / "data")))
SRC       = REPO_ROOT / "sources" / "table3"
ENGINE    = REPO_ROOT / "sources" / "drampower"
BUILD     = ENGINE / "build"
RUNNER    = BUILD / "bin" / "HBM2_runner"
OUT_DIR   = Path(os.environ.get("OUT_DIR", os.environ.get("FIG_DIR", str(REPO_ROOT / "figures"))))
OUT_DIR.mkdir(exist_ok=True)

CFG    = SRC / "configs"
ORG    = str(CFG / "HBM2_organization.json")
TIMING = str(CFG / "HBM2_1.2Gbps_timing_BL4.json")   # read-timing fix: nBL=4

# workload -> (trace stem, all-0s ground-truth test_name, random ground-truth test_name)
WORKLOADS = [
    ("act_hammer",          "act_hammer",          "act_hammer_rand"),
    ("interleaved",         "interleaved",         "interleaved_rand"),
    ("streaming_all_banks", "streaming_all_banks", "streaming_all_banks_4cyc_rand"),
    ("streaming_reads",     "streaming_reads",     "streaming_reads_4cyc_rand"),
    ("wr_rd_turnaround",    "wr_rd_turnaround",    "wr_rd_turnaround_4cyc_rand"),
    ("ws_bg0_bg2",          "ws_bg0_bg2",          "ws_bg0_bg2_rand"),
]
WORKLOADS += [
    (f"bs{bs}_ctx1024",
     f"llama8Bshort_runner_pc0_bs{bs}_ctx1024_data_zeros",
     f"llama8Bshort_runner_pc0_bs{bs}_ctx1024_data_rand1")
    for bs in (1, 2, 4, 8, 16, 32, 64, 128)
]

# model -> (display name, all-0s IDD config, random IDD config)
MODELS = [
    ("DRAMSim3",    "IDD_dramsim3.json",         "IDD_dramsim3.json"),
    ("FGDRAM HBM2", "IDD_oconnor_notoggle.json", "IDD_oconnor_50toggle.json"),
    ("Ours",        "IDD_ours_allzeros.json",    "IDD_ours_random.json"),
]


def ensure_runner():
    if RUNNER.exists():
        return
    print(f"[build] {RUNNER.name} not found; building DRAMPower engine (one-time)...", file=sys.stderr)
    subprocess.run(["cmake", "-S", str(ENGINE), "-B", str(BUILD), "-DCMAKE_BUILD_TYPE=Release",
                    "-DDRAMPOWER_BUILD_TESTS=OFF", "-DDRAMPOWER_BUILD_BENCHMARKS=OFF",
                    "-DDRAMPOWER_BUILD_CLI=ON"], check=True)
    subprocess.run(["cmake", "--build", str(BUILD), "--target", "HBM2_runner", "-j"], check=True)
    if not RUNNER.exists():
        sys.exit(f"build did not produce {RUNNER}")


def run_power(idd_cfg, trace):
    out = subprocess.run([str(RUNNER), ORG, TIMING, str(CFG / idd_cfg), trace],
                         capture_output=True, text=True)
    m = re.search(r"Average power:\s+([-\d.]+)\s+mW", out.stdout + out.stderr)
    if not m:
        raise RuntimeError(f"no power for {trace}:\n{out.stdout}\n{out.stderr}")
    return float(m.group(1))


def load_gt(path):
    gt = defaultdict(list)
    for row in csv.DictReader(open(path)):
        p = float(row["power_vdd_avg"])
        if p > 0:
            gt[row["test_name"]].append(p)
    return gt


def per_workload_mape(idd_cfg, tn_index):
    """min, max, mean of per-workload MAPE across all workloads."""
    gt = GT_ZEROS if tn_index == 1 else GT_RANDOM
    mapes = []
    for row in WORKLOADS:
        stem, tn = row[0], row[tn_index]
        pred = run_power(idd_cfg, str(SRC / "traces" / f"{stem}.csv"))
        meas = gt[tn]
        mapes.append(sum(abs(pred - x) / x * 100 for x in meas) / len(meas))
    return min(mapes), max(mapes), sum(mapes) / len(mapes)


def main():
    global GT_ZEROS, GT_RANDOM
    ensure_runner()
    GT_ZEROS  = load_gt(DATA_DIR / "ground_truth_allzeros.csv")
    GT_RANDOM = load_gt(DATA_DIR / "ground_truth_random.csv")

    L = [r"\begin{table}[t]", r"\centering",
         r"\caption{Per-workload MAPE summary across data regimes.}",
         r"\label{tab:mape_summary}",
         r"\resizebox{\textwidth}{!}{%",
         r"\begin{tabular}{llccc}", r"\hline",
         r"Model & Data Pattern & Min MAPE (\%) & Max MAPE (\%) & Avg MAPE (\%) \\", r"\hline"]
    for name, idd_zeros, idd_random in MODELS:
        zmin, zmax, zavg = per_workload_mape(idd_zeros, 1)
        rmin, rmax, ravg = per_workload_mape(idd_random, 2)
        L.append(f"\\multirow{{2}}{{*}}{{{name}}} & all-0s & {zmin:.1f} & {zmax:.1f} & {zavg:.1f} \\\\")
        L.append(f" & random & {rmin:.1f} & {rmax:.1f} & {ravg:.1f} \\\\")
        L.append(r"\hline")
        print(f"{name:12} all-0s  min={zmin:4.1f} max={zmax:4.1f} avg={zavg:4.1f}   "
              f"random min={rmin:4.1f} max={rmax:4.1f} avg={ravg:4.1f}")
    L += [r"\end{tabular}%", r"}", r"\end{table}"]
    tex = "\n".join(L)

    out = OUT_DIR / "table3.tex"
    out.write_text(tex + "\n")
    print("\n" + tex)
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
