#!/usr/bin/env python3
"""
Aggregate BRAM trace-runner power CSVs into the ground-truth files that
figure14.py and table3.py consume.

This is the *measured* side of the two trace-based artifacts (Fig 14 + Table 3).
It closes the gap flagged in AE_TRACE_FIGURES_HANDOFF.md 4.4: the trace runner
(run_trace_sweep.sh / run_bram_local.sh) writes per-trace power CSVs in one
schema/naming, and the plot scripts read `chip_id,test_name,power_vdd_avg` keyed
by specific `test_name`s. This converter bridges them for the single AE chip.

Pipeline
--------
    reprogram bram_tracer_chipN  ->  run_trace_sweep.sh  ->  results/*_bram.csv
        --(this script)-->  data/ground_truth_{allzeros,random}.csv
        --> scripts/figures/figure14.py  and  scripts/tables/table3.py

For every `<set>_<trace>_data_{zeros,rand1}_bram.csv` produced by the sweep, take
the average instantaneous VDD power over the LAST N rows (steady state, exactly
as make_trace_power_csv.py does), map (trace, init) -> the ground-truth
`test_name` per the AE_TRACE_FIGURES_HANDOFF.md 5 table, and write one
`chip_id,test_name,power_vdd_avg` row into the matching ground-truth CSV.

Only the 14 AE workloads are accepted (6 microbenchmarks + the 8-point
LLaMa3.1-8B decode batch sweep, ctx1024). Any other `*_bram.csv` in the results
tree (leftover ctx64/256/4096 runs, the 1-rank A100 trace, ...) is ignored so it
cannot pollute the ground truth.

Data-init -> file:
    _data_zeros -> ground_truth_allzeros.csv   (zeros init)
    _data_rand1 -> ground_truth_random.csv     (random init, seed 1)

The LLaMa rows are an identity map (the ground-truth name IS the runner stem);
only the 6 microbenchmarks need the rename (all-0s drops `_ramulator`/`_4cyc`;
random keeps `_4cyc` and adds `_rand`). Authoritative definitions:
scripts/figures/figure14.py MICRO and scripts/tables/table3.py WORKLOADS.

Write modes
-----------
  replace (default)  Write ONLY this chip's 14+14 rows, so the figures collapse
                     to single points -- the same single-chip treatment the IDD
                     figures get in run_fpga_ae.sh. The released full-fleet files
                     are backed up to data/released_backup/ first (idempotent).
  --merge            Upsert this chip's rows into the existing (fleet) file:
                     drop the rows already carrying this chip_id, append the new
                     ones, keep every other chip. Use this to overlay the AE
                     chip's points within the paper's cross-stack boxes.

Config (CLI flags override the matching environment variable):
  --results-dir / RESULTS_DIR   root to search for *_bram.csv (recursive)   [results]
  --data-dir    / DATA_DIR      artifact data/ dir (ground-truth output)    [<artifact>/data]
  --chip-id     / CHIP_ID       chip_id to tag the measured rows with       [0]
  --last-n      / LAST_N        steady-state rows to average per trace       [10]
  --merge                       upsert into the fleet file instead of replacing
  --no-backup                   do not copy released files to released_backup/
  -n / --dry-run                report what would be written, touch nothing

Exit codes: 0 success (rows written, even if some workloads were missing -- a
loud warning is printed); 1 configuration/plumbing error (no data dir, no
usable *_bram.csv at all).
"""

import argparse
import csv
import glob
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ARTIFACT_ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))   # HBM-Power/

# Canonical fleet fpga->chip_id map (generated by generate_standardized_csvs.py).
# Needed only in --fleet mode; pass --chip-map / set CHIP_MAP if not present here.
DEFAULT_CHIP_MAP = os.path.join(ARTIFACT_ROOT, "data", "chip_mapping.csv")

VDD_INS = "Power_VDD_Ins(mW)"          # same steady-state quantity as the fleet data
GT_HEADER = ["chip_id", "test_name", "power_vdd_avg"]

# --------------------------------------------------------------------------- #
# Trace -> test_name mapping (AE_TRACE_FIGURES_HANDOFF.md 5 -- the source of truth)
# --------------------------------------------------------------------------- #
# Microbenchmark runner basename -> (all-0s test_name, random test_name).
# The runner writes original_traces_<basename>_data_{zeros,rand1}_bram.csv.
MICRO_MAP = {
    "act_hammer_ramulator":               ("act_hammer",          "act_hammer_rand"),
    "interleaved_ramulator":              ("interleaved",         "interleaved_rand"),
    "streaming_all_banks_4cyc_ramulator": ("streaming_all_banks", "streaming_all_banks_4cyc_rand"),
    "streaming_reads_4cyc_ramulator":     ("streaming_reads",     "streaming_reads_4cyc_rand"),
    "wr_rd_turnaround_4cyc_ramulator":    ("wr_rd_turnaround",    "wr_rd_turnaround_4cyc_rand"),
    "ws_bg0_bg2_ramulator":               ("ws_bg0_bg2",          "ws_bg0_bg2_rand"),
}
LLM_BATCH_SIZES = (1, 2, 4, 8, 16, 32, 64, 128)
LLM_SET_PREFIX = "llama8Bshort_runner_pc0"   # must match run_trace_sweep.sh's LLM set label


def build_expected():
    """runner stem (basename minus _bram.csv) -> (target file key, test_name).

    28 entries: 14 workloads x {zeros, rand1}. Anything not in here is ignored.
    """
    expected = {}
    for micro, (name_z, name_r) in MICRO_MAP.items():
        expected[f"original_traces_{micro}_data_zeros"] = ("allzeros", name_z)
        expected[f"original_traces_{micro}_data_rand1"] = ("random",   name_r)
    for bs in LLM_BATCH_SIZES:
        stem_z = f"{LLM_SET_PREFIX}_bs{bs}_ctx1024_data_zeros"
        stem_r = f"{LLM_SET_PREFIX}_bs{bs}_ctx1024_data_rand1"
        expected[stem_z] = ("allzeros", stem_z)   # LLM: identity map
        expected[stem_r] = ("random",   stem_r)
    return expected


EXPECTED = build_expected()
TARGET_FILE = {"allzeros": "ground_truth_allzeros.csv",
               "random":   "ground_truth_random.csv"}


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #
def log(msg):  sys.stdout.write("aggregate: " + msg + "\n")
def warn(msg): sys.stderr.write("aggregate: WARNING: " + msg + "\n")
def fail(msg):
    sys.stderr.write("aggregate: ERROR: " + msg + "\n")
    sys.exit(1)


def stem_of(path):
    """.../original_traces_act_hammer_ramulator_data_zeros_bram.csv -> ..._data_zeros"""
    base = os.path.basename(path)
    if base.endswith("_bram.csv"):
        return base[: -len("_bram.csv")]
    if base.endswith(".csv"):
        return base[: -len(".csv")]
    return base


def steady_state_vdd(path, last_n):
    """Mean of the last `last_n` VDD_INS samples, or None if unreadable/too short."""
    with open(path, newline="") as fh:
        reader = csv.reader(fh)
        try:
            header = next(reader)
        except StopIteration:
            return None
        if VDD_INS not in header:
            return None
        col = header.index(VDD_INS)
        vals = []
        for row in reader:
            if len(row) <= col:
                continue
            try:
                vals.append(float(row[col]))
            except ValueError:
                continue
    if len(vals) < last_n:
        return None
    tail = vals[-last_n:]
    return round(sum(tail) / len(tail), 2)


def read_existing(path):
    """Read a ground-truth CSV into a list of [chip_id, test_name, power] string rows.

    Defensively drops any header-echo / malformed row (chip_id not an int or
    power not a float) so a leaked header line (AE_TRACE_FIGURES_HANDOFF.md 4.6)
    cannot survive a --merge round-trip.
    """
    rows = []
    if not os.path.isfile(path):
        return rows
    with open(path, newline="") as fh:
        for i, row in enumerate(csv.reader(fh)):
            if i == 0 and row[:3] == GT_HEADER:
                continue                     # real header
            if len(row) < 3:
                continue
            try:
                int(row[0]); float(row[2])
            except (ValueError, IndexError):
                continue                     # header echo or junk -> drop
            rows.append([row[0], row[1], row[2]])
    return rows


def backup_released(data_dir, do_backup):
    """Copy released ground-truth files to data/released_backup/ once (idempotent)."""
    if not do_backup:
        return
    bdir = os.path.join(data_dir, "released_backup")
    for fname in TARGET_FILE.values():
        src = os.path.join(data_dir, fname)
        dst = os.path.join(bdir, fname)
        if os.path.isfile(src) and not os.path.isfile(dst):
            os.makedirs(bdir, exist_ok=True)
            shutil.copy2(src, dst)
            log(f"backed up released {fname} -> released_backup/")


def load_chip_map(path, chip_in_fpga):
    """Read chip_mapping.csv -> {fpga_name: chip_id} for the given stack (0/1).

    chip_mapping.csv columns: fpga_name,chip_in_fpga,chip_id. Only the rows whose
    chip_in_fpga matches the stack this pass measured are returned (chip0 bitstream
    -> chip_in_fpga 0 -> even chip_ids; chip1 -> 1 -> odd).
    """
    if not os.path.isfile(path):
        fail(f"chip map not found: {path}\n"
             "       Pass --chip-map / set CHIP_MAP, or regenerate chip_mapping.csv\n"
             "       (generate_standardized_csvs.py's generate_chip_mapping_csv).")
    mapping = {}
    with open(path, newline="") as fh:
        reader = csv.DictReader(fh)
        need = {"fpga_name", "chip_in_fpga", "chip_id"}
        if not need.issubset(reader.fieldnames or []):
            fail(f"chip map {path} missing columns {need - set(reader.fieldnames or [])}")
        for row in reader:
            try:
                if int(row["chip_in_fpga"]) != int(chip_in_fpga):
                    continue
                mapping[row["fpga_name"]] = int(row["chip_id"])
            except (ValueError, KeyError):
                continue
    if not mapping:
        fail(f"chip map {path} has no rows for chip_in_fpga={chip_in_fpga}")
    return mapping


def write_gt(path, header_rows, chip_ids, new_rows, merge, dry_run):
    """Write `new_rows` (list of [chip_id,test_name,power]) into `path`.

    `chip_ids` is the set (of str) of chip_ids these new_rows cover. merge=False ->
    file holds only new_rows. merge=True -> keep every row whose chip_id is NOT in
    `chip_ids` (other chips / the other stack), replace the ones that are.
    """
    chip_ids = {str(c) for c in chip_ids}
    if merge:
        kept = [r for r in header_rows if r[0] not in chip_ids]
        out = kept + new_rows
    else:
        out = list(new_rows)
    # deterministic: by chip_id (numeric) then test_name
    out.sort(key=lambda r: (int(r[0]), r[1]))
    if dry_run:
        log(f"(dry-run) would write {len(out)} rows -> {path}")
        return
    with open(path, "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(GT_HEADER)
        w.writerows(out)
    log(f"wrote {len(out)} rows -> {os.path.relpath(path, ARTIFACT_ROOT)}")


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #
def parse_args():
    p = argparse.ArgumentParser(add_help=True, description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--results-dir", default=os.environ.get("RESULTS_DIR",
                   os.path.join(ARTIFACT_ROOT, "results")))
    p.add_argument("--data-dir", default=os.environ.get("DATA_DIR",
                   os.path.join(ARTIFACT_ROOT, "data")))
    p.add_argument("--chip-id", type=int, default=int(os.environ.get("CHIP_ID", "0")))
    p.add_argument("--last-n", type=int, default=int(os.environ.get("LAST_N", "10")))
    p.add_argument("--fleet", action="store_true",
                   help="aggregate ALL results/safari-fpga<N>/ dirs, mapping each "
                        "fpga->chip_id via --chip-map (instead of a single --chip-id)")
    p.add_argument("--chip-in-fpga", type=int, choices=(0, 1),
                   default=int(os.environ.get("CHIP_IN_FPGA", "0")),
                   help="[fleet] which stack this pass measured: 0=chip0 bitstream "
                        "(even chip_ids), 1=chip1 (odd). Default 0.")
    p.add_argument("--chip-map", default=os.environ.get("CHIP_MAP", DEFAULT_CHIP_MAP),
                   help="[fleet] chip_mapping.csv (fpga_name,chip_in_fpga,chip_id)")
    p.add_argument("--merge", action="store_true",
                   help="upsert this chip/stack into the fleet file instead of "
                        "replacing (use for the 2nd stack pass to keep the 1st)")
    p.add_argument("--no-backup", action="store_true",
                   help="do not copy released files to released_backup/")
    p.add_argument("-n", "--dry-run", action="store_true")
    return p.parse_args()


def run_fleet(args):
    """Fleet mode: aggregate every results/safari-fpga<N>/ dir into all chips'
    rows of ground_truth_{allzeros,random}.csv, mapping fpga->chip_id per stack."""
    if not os.path.isdir(args.data_dir):
        fail(f"data dir not found: {args.data_dir}")
    if not os.path.isdir(args.results_dir):
        fail(f"results dir not found: {args.results_dir}\n"
             "       Point --results-dir at the fleet trace results "
             "(contains safari-fpga<N>/ subdirs of *_bram.csv).")

    chip_of = load_chip_map(args.chip_map, args.chip_in_fpga)
    fpga_dirs = sorted(glob.glob(os.path.join(args.results_dir, "safari-fpga*")))
    fpga_dirs = [d for d in fpga_dirs if os.path.isdir(d)]
    if not fpga_dirs:
        fail(f"no safari-fpga<N>/ subdirs under {args.results_dir}\n"
             "       Fleet mode expects copy_results.sh's per-host layout; "
             "for a single flat dir use single-chip mode (--chip-id).")

    log(f"FLEET  chip_in_fpga={args.chip_in_fpga}  last_n={args.last_n}  "
        f"mode={'merge' if args.merge else 'replace'}  chip_map={os.path.relpath(args.chip_map, ARTIFACT_ROOT)}")
    log(f"scanning {len(fpga_dirs)} fpga dir(s) under {args.results_dir}")

    # file key -> chip_id(int) -> {test_name: power}
    measured = {"allzeros": {}, "random": {}}
    ignored, unreadable, dup, unmapped, empty = [], [], [], [], []
    for fdir in fpga_dirs:
        fname = os.path.basename(fdir)
        cid = chip_of.get(fname)
        if cid is None:
            unmapped.append(fname)
            continue
        csvs = sorted(glob.glob(os.path.join(fdir, "**", "*_bram.csv"), recursive=True))
        if not csvs:
            empty.append(fname)
            continue
        for path in csvs:
            target = EXPECTED.get(stem_of(path))
            if target is None:
                ignored.append(os.path.basename(path))
                continue
            file_key, test_name = target
            vdd = steady_state_vdd(path, args.last_n)
            if vdd is None:
                unreadable.append(f"{fname}/{os.path.basename(path)}")
                continue
            slot = measured[file_key].setdefault(cid, {})
            if test_name in slot:
                dup.append(f"chip{cid}:{test_name}")
            slot[test_name] = vdd

    if unmapped:
        warn(f"{len(unmapped)} result dir(s) not in chip map (skipped): "
             + ", ".join(sorted(unmapped)))
    if empty:
        warn(f"{len(empty)} fpga dir(s) had no *_bram.csv: " + ", ".join(sorted(empty)))
    if ignored:
        log(f"ignored {len(ignored)} non-AE *_bram.csv "
            f"({len(set(ignored))} distinct name(s))")
    for f in unreadable:
        warn(f"unreadable / too few rows, skipped: {f}")
    for t in sorted(set(dup)):
        warn(f"multiple *_bram.csv mapped to '{t}'; kept the last one")

    total = sum(len(tests) for chips in measured.values() for tests in chips.values())
    if total == 0:
        fail("found fpga dirs but no *_bram.csv matched an AE workload trace name.\n"
             "       Check the sweep output naming vs the 5 mapping.")

    # completeness: 14 workloads expected per chip per file
    for file_key in ("allzeros", "random"):
        want = {tn for (fk, tn) in EXPECTED.values() if fk == file_key}
        chips = measured[file_key]
        complete = [c for c in chips if not (want - set(chips[c]))]
        incomplete = sorted(set(chips) - set(complete))
        log(f"{TARGET_FILE[file_key]}: {len(chips)} chip(s), "
            f"{len(complete)} complete ({len(want)}/{len(want)} workloads)")
        for c in incomplete:
            missing = sorted(want - set(chips[c]))
            warn(f"  chip {c} missing {len(missing)}: " + ", ".join(missing))
        if incomplete:
            warn("  figure14.py / table3.py error on any missing workload -- "
                 "re-run the sweep for the chips above before plotting.")

    backup_released(args.data_dir, not args.no_backup and not args.dry_run)
    for file_key in ("allzeros", "random"):
        path = os.path.join(args.data_dir, TARGET_FILE[file_key])
        existing = read_existing(path) if args.merge else []
        new_rows, chip_ids = [], set()
        for cid, tests in sorted(measured[file_key].items()):
            chip_ids.add(str(cid))
            for tn, p in tests.items():
                new_rows.append([str(cid), tn, f"{p}"])
        write_gt(path, existing, chip_ids, new_rows, args.merge, args.dry_run)

    log("done." + (" (dry run -- nothing written)" if args.dry_run else ""))


def main():
    args = parse_args()

    if args.fleet:
        run_fleet(args)
        return

    if not os.path.isdir(args.data_dir):
        fail(f"data dir not found: {args.data_dir}")
    if not os.path.isdir(args.results_dir):
        fail(f"results dir not found: {args.results_dir}\n"
             "       Point --results-dir at the copied trace results (contains *_bram.csv).")

    csvs = sorted(glob.glob(os.path.join(args.results_dir, "**", "*_bram.csv"),
                            recursive=True))
    if not csvs:
        fail(f"no *_bram.csv found under {args.results_dir}\n"
             "       Did run_trace_sweep.sh run and copy_results.sh --trace pull them back?")

    log(f"chip_id={args.chip_id}  last_n={args.last_n}  "
        f"mode={'merge' if args.merge else 'replace'}")
    log(f"scanning {len(csvs)} *_bram.csv under {args.results_dir}")

    # collect measured rows per target file
    measured = {"allzeros": {}, "random": {}}   # file key -> {test_name: power}
    ignored, unreadable, dup = [], [], []
    for path in csvs:
        stem = stem_of(path)
        target = EXPECTED.get(stem)
        if target is None:
            ignored.append(os.path.basename(path))
            continue
        file_key, test_name = target
        vdd = steady_state_vdd(path, args.last_n)
        if vdd is None:
            unreadable.append(os.path.basename(path))
            continue
        if test_name in measured[file_key]:
            dup.append(test_name)
        measured[file_key][test_name] = vdd

    if ignored:
        log(f"ignored {len(ignored)} non-AE *_bram.csv "
            f"(leftover/other-workload traces): {', '.join(sorted(set(ignored))[:6])}"
            + (" ..." if len(set(ignored)) > 6 else ""))
    for f in unreadable:
        warn(f"unreadable / too few rows, skipped: {f}")
    for t in sorted(set(dup)):
        warn(f"multiple *_bram.csv mapped to test_name '{t}'; kept the last one")

    total = sum(len(v) for v in measured.values())
    if total == 0:
        fail("found *_bram.csv but none matched an AE workload trace name.\n"
             "       Check run_trace_sweep.sh output naming vs the 5 mapping.")

    # completeness report (per file: 14 expected)
    for file_key in ("allzeros", "random"):
        want = {tn for (fk, tn) in EXPECTED.values() if fk == file_key}
        got = set(measured[file_key])
        missing = sorted(want - got)
        log(f"{TARGET_FILE[file_key]}: {len(got)}/{len(want)} workloads measured")
        if missing:
            warn(f"{TARGET_FILE[file_key]} missing {len(missing)} workload(s): "
                 + ", ".join(missing))
            warn("  figure14.py / table3.py will error on a missing workload -- "
                 "re-run the sweep for these before plotting.")

    # write
    backup_released(args.data_dir, not args.no_backup and not args.dry_run)
    for file_key in ("allzeros", "random"):
        path = os.path.join(args.data_dir, TARGET_FILE[file_key])
        existing = read_existing(path) if args.merge else []
        new_rows = [[str(args.chip_id), tn, f"{p}"]
                    for tn, p in measured[file_key].items()]
        write_gt(path, existing, {args.chip_id}, new_rows, args.merge, args.dry_run)

    log("done." + (" (dry run -- nothing written)" if args.dry_run else ""))


if __name__ == "__main__":
    main()
